modLoader="javafml" 
loaderVersion="[35,)" 
issueTrackerURL="https://github.com/MysticMods/Traverse/issues"
license="https://github.com/MysticMods/Traverse/blob/master/LICENSE"
[[mods]] 
modId="traverse" 
version="${file.jarVersion}" 
displayName="Traverse: Reforged"
credits="Prospector & Traverse Team"
authors="Prospector, Noobanidus, EpicSquid, Androsa"
description='''
A collection of vanilla style biomes to spruce up your world.
'''
[[dependencies.traverse]] 
    modId="forge" 
    mandatory=true 
    versionRange="[35,)" 
    ordering="NONE"
    side="BOTH"
[[dependencies.traverse]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,)"
    ordering="NONE"
    side="BOTH"
